Name:           ros-indigo-pr2-calibration-launch
Version:        1.0.9
Release:        0%{?dist}
Summary:        ROS pr2_calibration_launch package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/pr2_calibration_launch
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-calibration-estimation
Requires:       ros-indigo-calibration-launch
Requires:       ros-indigo-calibration-msgs
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-image-cb-detector
Requires:       ros-indigo-image-view
Requires:       ros-indigo-kdl-parser
Requires:       ros-indigo-laser-cb-detector
Requires:       ros-indigo-laser-joint-processor
Requires:       ros-indigo-laser-joint-projector
Requires:       ros-indigo-message-runtime
Requires:       ros-indigo-monocam-settler
Requires:       ros-indigo-pr2-dense-laser-snapshotter
Requires:       ros-indigo-pr2-teleop
Requires:       ros-indigo-python-orocos-kdl
Requires:       ros-indigo-robot-mechanism-controllers
Requires:       ros-indigo-rospy
Requires:       ros-indigo-rostest
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-stereo-image-proc
BuildRequires:  ros-indigo-calibration-estimation
BuildRequires:  ros-indigo-calibration-launch
BuildRequires:  ros-indigo-calibration-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-image-cb-detector
BuildRequires:  ros-indigo-image-view
BuildRequires:  ros-indigo-kdl-parser
BuildRequires:  ros-indigo-laser-cb-detector
BuildRequires:  ros-indigo-laser-joint-processor
BuildRequires:  ros-indigo-laser-joint-projector
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-monocam-settler
BuildRequires:  ros-indigo-pr2-dense-laser-snapshotter
BuildRequires:  ros-indigo-pr2-teleop
BuildRequires:  ros-indigo-python-orocos-kdl
BuildRequires:  ros-indigo-robot-mechanism-controllers
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-rostest
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-stereo-image-proc

%description
Launch files and configuration files needed to run the calibration pipeline on
PR2. This package is still experimental. Expect large changes tp occur.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Feb 06 2015 Devon Ash <dash@clearpathrobotics.com> - 1.0.9-0
- Autogenerated by Bloom

