Name:           ros-hydro-pr2-calibration-launch
Version:        1.0.4
Release:        0%{?dist}
Summary:        ROS pr2_calibration_launch package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/pr2_calibration_launch
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-calibration-estimation
Requires:       ros-hydro-calibration-launch
Requires:       ros-hydro-calibration-msgs
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-image-cb-detector
Requires:       ros-hydro-image-view
Requires:       ros-hydro-kdl-parser
Requires:       ros-hydro-laser-cb-detector
Requires:       ros-hydro-laser-joint-processor
Requires:       ros-hydro-laser-joint-projector
Requires:       ros-hydro-message-runtime
Requires:       ros-hydro-monocam-settler
Requires:       ros-hydro-pr2-dense-laser-snapshotter
Requires:       ros-hydro-pr2-teleop
Requires:       ros-hydro-python-orocos-kdl
Requires:       ros-hydro-robot-mechanism-controllers
Requires:       ros-hydro-rospy
Requires:       ros-hydro-rostest
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-stereo-image-proc
BuildRequires:  ros-hydro-calibration-estimation
BuildRequires:  ros-hydro-calibration-launch
BuildRequires:  ros-hydro-calibration-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-image-cb-detector
BuildRequires:  ros-hydro-image-view
BuildRequires:  ros-hydro-kdl-parser
BuildRequires:  ros-hydro-laser-cb-detector
BuildRequires:  ros-hydro-laser-joint-processor
BuildRequires:  ros-hydro-laser-joint-projector
BuildRequires:  ros-hydro-message-generation
BuildRequires:  ros-hydro-monocam-settler
BuildRequires:  ros-hydro-pr2-dense-laser-snapshotter
BuildRequires:  ros-hydro-pr2-teleop
BuildRequires:  ros-hydro-python-orocos-kdl
BuildRequires:  ros-hydro-robot-mechanism-controllers
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-rostest
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-stereo-image-proc

%description
Launch files and configuration files needed to run the calibration pipeline on
PR2. This package is still experimental. Expect large changes tp occur.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Sep 17 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.4-0
- Autogenerated by Bloom

* Thu Sep 11 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.3-0
- Autogenerated by Bloom

* Mon Sep 08 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.2-0
- Autogenerated by Bloom

