# ----- Forearm Camera Right (Rectified)-----
forearm_right_rect:
  cb_detector_config:  /r_forearm_cam/cb_detector_config
  led_detector_config: /r_forearm_cam/led_detector
  settler_config:      /r_forearm_cam/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 2
        height_scaling: 2
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 1
        height_scaling: 1
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False

# ----- Microsoft Kinect -----
kinect_rect:
  cb_detector_config:  /camera/rgb/cb_detector_config
  led_detector_config: /camera/rgb/led_detector
  settler_config:      /camera/rgb/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 3.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 0.5
        height_scaling: 0.5
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 3.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 0.5
        height_scaling: 0.5
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False

# ----- Prosilica (Rectified) -----
prosilica_rect:
  cb_detector_config:  /prosilica/cb_detector_config
  led_detector_config: /prosilica/led_detector
  settler_config:      /prosilica/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 3.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 0.5
        height_scaling: 0.5
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 3.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 0.5
        height_scaling: 0.5
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False

